server:
  service:
    type: ClusterIP

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 150m
      memory: 256Mi

  insecure: true

  extraArgs:
    - --insecure


controller:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi

repoServer:

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 150m
      memory: 256Mi

  volumes:
    - name: cmp-plugin
      configMap:
        name: servicenow-plugin

  extraContainers:
    - name: servicenow-plugin
      image: quay.io/argoproj/argocd:v3.3.0
      command: ["/var/run/argocd/argocd-cmp-server"]

      env:
        - name: SERVICENOW_INSTANCE
          value: "https://dev306695.service-now.com"

        - name: SERVICENOW_USER
          valueFrom:
            secretKeyRef:
              name: servicenow-creds
              key: username

        - name: SERVICENOW_PASSWORD
          valueFrom:
            secretKeyRef:
              name: servicenow-creds
              key: password

      volumeMounts:
        - name: plugins
          mountPath: /home/argocd/cmp-server/plugins

        - name: cmp-plugin
          mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: plugin.yaml


  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 150m
      memory: 256Mi

applicationSet:
  enabled: false


notifications:
  enabled: false


configs:
  cm:
    url: http://localhost:8080

    oidc.config: |
      name: Keycloak
      issuer: http://keycloak.keycloak.svc.cluster.local/realms/argocd
      clientID: argocd
      clientSecret: ""
      requestedScopes: ["openid", "profile", "email"]
      requestedIDTokenClaims:
        roles:
          essential: true

    # user sre = admin
    accounts.sre: login
    accounts.sre.enabled: "true"

    accounts.servicenow: apiKey
    accounts.servicenow.enabled: "true"

  rbac:
    policy.default: role:readonly
    scopes: '[roles]'
    policy.csv: |
      g, sre, role:admin

      p, role:servicenow-role, applications, get, *, allow
      p, role:servicenow-role, applications, sync, *, allow
      p, role:servicenow-role, applications, create, *, allow
      p, role:servicenow-role, applications, update, *, allow

      g, servicenow, role:servicenow-role
      g, gs_argocd_admin, role:admin
      g, gs_argocd_ro, role:readonly

      p, role:admin, *, *, *, allow