#global:
#  domain: argocd.local

server:
  service:
    type: ClusterIP

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 150m
      memory: 256Mi

  insecure: true

  extraArgs:
    - --insecure

controller:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi

repoServer:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 150m
      memory: 256Mi

applicationSet:
  enabled: false

notifications:
  enabled: false

configs:
  cm:
    # user sre = admin
    accounts.sre: login
    accounts.sre.enabled: "true"

    # user SNOW
    accounts.servicenow: apiKey
    accounts.servicenow.enabled: "true"

  rbac:
    policy.default: role:readonly
    policy.csv: |
      # SRE com acesso total
      g, sre, role:admin

      # Role específica para ServiceNow
      p, role:servicenow-role, applications, get, *, allow
      p, role:servicenow-role, applications, sync, *, allow
      p, role:servicenow-role, applications, create, *, allow
      p, role:servicenow-role, applications, update, *, allow

      g, servicenow, role:servicenow-role