apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: principal-ingress
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - http:
      paths:
      - path: /nginx
        pathType: Prefix
        backend:
          service:
            name: nginx-teste-lb
            port:
              number: 80
