apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: apps
spec:
  type: NodePort
  selector:
    app: podinfo
  ports:
    - port: 9898
      targetPort: 9898
      nodePort: 9898
